---
title: "Scatterplots"
author: "Ellen Considine"
date: "3/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(cowplot)
library(stringr)
# library(ggrepel)

valid<- readRDS("Revisions_Merged_FINAL_monitor_Di_Reid_with_CMAQ.rds")

## Capitalizing
names(valid)[which(names(valid) == "year")]<- "Year"
names(valid)[which(names(valid) == "season")]<- "Season"
names(valid)[which(names(valid) == "state")]<- "State"

# valid$State<- str_to_title(valid$State)

## Adjust Season labels:

valid$Season<- "Cold"
valid$Season[which(valid$Warm_season == TRUE)]<- "Warm"

```

```{r}

CBF<- palette.colors()# color-blind friendly palette

## Make scatterplots with different colors by different variables:

plot_3_combos<- function(df, col_var, shape_var){
  
  d1<- mcreg(df$PM2.5,df$PM_Di, method.reg = "Deming",  na.rm=TRUE)@para
  d2<- mcreg(df$PM2.5,df$PM_Reid, method.reg = "Deming",  na.rm=TRUE)@para
  d3<- mcreg(df$PM_Reid,df$PM_Di, method.reg = "Deming",  na.rm=TRUE)@para
  
  if(col_var == "Season"){
    
    p1<- ggplot(df,
              aes_string(x="PM2.5", y="PM_Di", color = col_var, shape = shape_var))+
    geom_point()+geom_abline(intercept=0,slope=1)+ 
      ylim(c(0,400)) + xlim(c(0,1000)) +
      geom_text(x=250, y=175, label="y=x", col = "black") +
      geom_abline(intercept = d1[1], slope = d1[2], col = "#009E73") +
      geom_text(x=900, y=125, label="Best fit", col = "#009E73") + 
      geom_text(x=900, y=60, label=paste("slope =", round(d1[2],2)), col = "#009E73") +
    ggtitle("Di vs. Monitor") + xlab("Validation PM2.5") +
    ylab("Di Estimates") + scale_color_manual(values = c("skyblue", "orange"))
    
    p2<- ggplot(df,
              aes_string(x="PM2.5",y="PM_Reid", color = col_var, shape = shape_var))+
    geom_point()+ geom_abline(intercept=0,slope=1)+
      ylim(c(0,400)) + xlim(c(0,1000)) +
      geom_text(x=225, y=275, label="y=x", col = "black") +
      geom_abline(intercept = d2[1], slope = d2[2], col = "#009E73") +
      geom_text(x=900, y=245, label="Best fit", col = "#009E73") +
      geom_text(x=900, y=150, label=paste("slope =", round(d2[2],2)), col = "#009E73") +
    ggtitle("Reid vs. Monitor") + xlab("Validation PM2.5") +
    ylab("Reid Estimates") + scale_color_manual(values = c("skyblue", "orange")) 
    
    shape_info<- rep(16,2)
    
    p3<- ggplot(df,
              aes_string(x="PM_Reid", y="PM_Di", color = col_var, shape = shape_var))+
    geom_point()+ geom_abline(intercept=0,slope=1)+
      ylim(c(0,200)) + xlim(c(0,500)) +
      geom_text(x=200, y=175, label="y=x", col = "black") +
      geom_abline(intercept = d3[1], slope = d3[2], col = "#009E73") +
      geom_text(x=350, y=185, label="Best fit", col = "#009E73") +
      geom_text(x=425, y=150, label=paste("slope =", round(d3[2],2)), col = "#009E73") +
    ggtitle("Di vs. Reid") + xlab("Reid Estimates") +
    ylab("Di Estimates") + guides(shape = "none") +
      scale_color_manual(values = c("skyblue", "orange"), name = "Season") 
    this_leg<- get_legend(p3 +
                        theme(legend.position = "bottom", legend.box = "vertical",
                               legend.key.width = unit(0.25, "line"), 
                              legend.spacing.y = unit(0.1, "cm")))
    
  }else{
    col_ramp<- colorRampPalette(c("pink", "blue"))
    
    p1<- ggplot(df,
              aes_string(x="PM2.5", y="PM_Di", color = col_var, shape = shape_var))+
    geom_point()+geom_abline(intercept=0,slope=1)+
      ylim(c(0,400)) + xlim(c(0,1000)) +
      geom_text(x=250, y=175, label="y=x", col = "black") +
      geom_abline(intercept = d1[1], slope = d1[2], col = "#009E73") +
      geom_text(x=900, y=125, label="Best fit", col = "#009E73") +
      geom_text(x=900, y=60, label=paste("slope =", round(d1[2],2)), col = "#009E73") +
    ggtitle("Di vs. Monitor") + xlab("Validation PM2.5") +
    ylab("Di Estimates") + scale_colour_gradientn(colors = col_ramp(20))
    
    p2<- ggplot(df,
              aes_string(x="PM2.5",y="PM_Reid", color = col_var, shape = shape_var))+
    geom_point()+ geom_abline(intercept=0,slope=1)+
      ylim(c(0,400)) + xlim(c(0,1000)) +
      geom_text(x=225, y=275, label="y=x", col = "black") +
      geom_abline(intercept = d2[1], slope = d2[2], col = "#009E73") +
      geom_text(x=900, y=245, label="Best fit", col = "#009E73") +
      geom_text(x=900, y=150, label=paste("slope =", round(d2[2],2)), col = "#009E73") +
    ggtitle("Reid vs. Monitor") + xlab("Validation PM2.5") +
    ylab("Reid Estimates") + scale_colour_gradientn(colors = col_ramp(20))
    
    shape_info<- rep(16,5)
    
    p3<- ggplot(df,
              aes_string(x="PM_Reid", y="PM_Di", color = col_var, shape = shape_var))+
    geom_point()+ geom_abline(intercept=0,slope=1)+
      ylim(c(0,200)) + xlim(c(0,500)) +
      geom_text(x=200, y=175, label="y=x", col = "black") +
      geom_abline(intercept = d3[1], slope = d3[2], col = "#009E73") +
      geom_text(x=350, y=185, label="Best fit", col = "#009E73") +
      geom_text(x=425, y=150, label=paste("slope =", round(d3[2],2)), col = "#009E73") +
    ggtitle("Di vs. Reid") + xlab("Reid Estimates") +
    ylab("Di Estimates") + guides(shape = "none") + 
      scale_colour_gradientn(colors = col_ramp(20))
    
    this_leg<- get_legend(p3 + theme(legend.position = "bottom",
                                     legend.key.width = unit(1.25, "cm")))
  }
  
  plot_grid(p1 + theme(legend.position="none"),
            p2 + theme(legend.position="none"),
            p3 + theme(legend.position="none"),
            this_leg, nrow = 4, rel_heights = c(1,1,1,0.25))
}

## Make plots:
valid$pch<- 16
valid$pch[which(valid$State > "Nevada")]<- 17
valid$pch<- factor(valid$pch)
valid$State<- factor(valid$State)

# png("Plots/Scatterplots_state-colors.png", width=350, height=700)
# plot_3_combos(valid, "State", "pch")
# dev.off()

valid$ones<- factor(1)
valid$Year<- as.numeric(valid$Year)
png("Plots/Scatterplots_year-colors.png", width=350, height=700)
plot_3_combos(valid[order(valid$Year, decreasing = TRUE),], "Year", "ones")
dev.off()

png("Plots/Scatterplots_WS-colors.png", width=350, height=700)
plot_3_combos(valid[order(valid$Warm_season, decreasing = TRUE),], "Season", "ones")
dev.off()

```

```{r}
## Map of validation monitor locations?

library(maps)

states<-c('arizona','california','colorado','idaho','montana','nevada','new mexico','oregon','utah','washington','wyoming')

west<- map_data("state", region = states)
valid$Days<- 1
Locations<- aggregate(Days ~ longitude + latitude, valid, sum)

png("Plots/Validation_Monitor_Obs.png", width=500, height=400)

ggplot() + geom_polygon(data=west, aes(x=long, y=lat, group = group), 
                                  color="black", fill = "white") + 
  geom_point(data = Locations, aes(x=longitude, y=latitude, 
                                   color = Days)) +
  scale_color_gradient(low="white", high="navy blue", trans = "log10") +
  ggtitle("Map of Validation Monitor Observations") + theme_bw() +
  xlab("Longitude") + ylab("Latitude")

dev.off()

```



