---
title: "Final data processing"
author: "Ellen Considine"
date: "2/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(lubridate)
library(ggplot2)
library(cowplot)
library(xtable)
library(stringr)

## Set working directory to GitHub repo folder


```

```{r}
#### Read in the datasets...

## PM2.5 obs used in training the Reid model:

Reid_obs<- readRDS("PM25_inputs.rds")
Reid_obs<- Reid_obs[,c("Lat", "Lon", "PM2.5_Obs", "Year", "Date_Local",
               "Data_Source_Name_Display")]

## Di and Reid estimates nearest to each PM2.5 observation in our validation set (from Airsis and WRCC):

di_valid<- readRDS("monitor_di_2008_2016.rds") # 29034
reid_valid<- readRDS("monitor_reid_wo_CMAQ.rds") # 44553 (without CMAQ: 2008-2018)

```


```{r}

#### Removing overlap between each set of estimates with the Reid training data:

di_valid$date<- as.Date(di_valid$date, format = "%Y-%m-%d")
reid_valid$date<- as.Date(reid_valid$date, format = "%Y-%m-%d")

Reid_obs$Date<- as.Date(Reid_obs$Date_Local, format = "%Y-%m-%d")
Reid_obs$Date_Local<- NULL

di_valid$row_id<- 1:nrow(di_valid)
reid_valid$row_id<- 1:nrow(reid_valid)

di_valid[,c("Lon", "Lat",
            "longitude", "latitude",
            "PM2.5")]<- apply(di_valid[,c("Lon", "Lat", 
                                                          "longitude", "latitude",
                                          "PM2.5")],
                                              MARGIN = 2, as.numeric)

di_valid$longitude<- round(di_valid$longitude, 4)
di_valid$latitude<- round(di_valid$latitude, 5)
reid_valid$longitude<- round(reid_valid$longitude, 4)
reid_valid$latitude<- round(reid_valid$latitude, 5)
Reid_obs$Lon<- round(Reid_obs$Lon, 4)
Reid_obs$Lat<- round(Reid_obs$Lat, 5)

di_overlap<- inner_join(di_valid, Reid_obs, by = c("longitude" = "Lon", 
                                                   "latitude" = "Lat",
                                                  "date" = "Date"))

reid_overlap<- inner_join(reid_valid, Reid_obs, by = c("longitude" = "Lon",
                                                  "latitude" = "Lat",
                                                  "date" = "Date"))

# table(di_overlap$Data_Source_Name_Display)
# table(di_overlap$state)
# 
# table(reid_overlap$Data_Source_Name_Display)
# table(reid_overlap$stateCode)

di_valid<- di_valid[which(!di_valid$row_id %in% di_overlap$row_id),] # 26899 obs
reid_valid<- reid_valid[which(!reid_valid$row_id %in% reid_overlap$row_id),] # 41179 obs

saveRDS(di_valid, "Monitors_Di_validation.rds")
saveRDS(reid_valid, "Monitors_Reid_wo_CMAQ.rds")


## Now for the Reid-with-CMAQ estimates (2008-2016):

reid_16<- readRDS("combine.rds") # readRDS("Validation_set.rds")
reid_16$date<- as.Date(reid_16$date, format = "%Y-%m-%d")
reid_16$longitude<- round(reid_16$longitude, 4)
reid_16$latitude<- round(reid_16$latitude, 5)
reid_16$row_id<- 1:nrow(reid_16)

reid_16_overlap<- inner_join(reid_16, Reid_obs, by = c("longitude" = "Lon",
                                                  "latitude" = "Lat",
                                                  "date" = "Date"))
reid_16_valid<- reid_16[which(!reid_16$row_id %in% reid_16_overlap$row_id),] # 26863 obs

```

```{r}
#### Check distances + days of included vs excluded AirFire points:

library(fields)

check_dists<- function(df1, df2){
  DF1<- as.matrix(distinct(df1))
  DF2<- as.matrix(distinct(df2))
  n1<- nrow(DF1)
  n2<- nrow(DF2)
  closeby<- matrix(0, nrow=1, ncol=5)
  
  for(i in 1:n2){
      dists<- rdist.earth.vec(DF1, cbind(rep(DF2[i,1], n1), 
                                         rep(DF2[i,2], n1)), miles=FALSE)
      pos<- which(dists <= 0.05) # within 50m
      if(length(pos) > 0){
        closeby<- rbind(closeby, cbind(DF1[pos,1], DF1[pos,2], 
                                       rep(DF2[i,1],length(pos)),
                                      rep(DF2[i,2],length(pos)), dists[pos]))
      }
      # print(paste(i, length(pos)))
    }

  return(closeby[-1,])
}

di_closeby<- check_dists(di_overlap[,c("longitude", "latitude")],
                         di_valid[,c("longitude", "latitude")])
reid_16_closeby<- check_dists(reid_16_overlap[,c("longitude", "latitude")],
                         reid_16_valid[,c("longitude", "latitude")])
reid_closeby<- check_dists(reid_overlap[,c("longitude", "latitude")],
                         reid_valid[,c("longitude", "latitude")])

get_final<- function(closeby, df1, df2){
  del_pos<- c()
  for(i in 1:nrow(closeby)){
    dates1<- df1[which(df1$longitude == closeby[i,1] & df1$latitude == closeby[i,2]),
                 "date"]
    dates2<- df2[which(df2$longitude == closeby[i,3] & df2$latitude == closeby[i,4]),
                 "date"]
    if(length(dates1) <= length(dates2)){
      Dates1<- unique(unlist(lapply(dates1, 
                                    function(d) seq.Date(d-7, d+7, by = "day"))))
      del_days<- dates2[which(dates2 %in% Dates1)]
    }else{
      Dates2<- unique(unlist(lapply(dates2, 
                                    function(d) seq.Date(d-7, d+7, by = "day"))))
      del_days<- dates1[which(dates1 %in% Dates2)]
    }
    
    del_pos<- append(del_pos, which(df2$longitude == closeby[i,3] & 
                                      df2$latitude == closeby[i,4] & 
                                      df2$date %in% del_days))
  }
  
  return(del_pos)
}

di_del_pos<- get_final(di_closeby, di_overlap[,c("longitude", "latitude", "date")],
                         di_valid[,c("longitude", "latitude", "date")])
reid_16_del_pos<- get_final(reid_16_closeby, 
                            reid_16_overlap[,c("longitude", "latitude", "date")],
                         reid_16_valid[,c("longitude", "latitude", "date")])
reid_del_pos<- get_final(reid_closeby, 
                         reid_overlap[,c("longitude", "latitude", "date")],
                         reid_valid[,c("longitude", "latitude", "date")])

```

```{r}

#### Merge and clean the final datasets...

## Merge 2008-2016 data (Di and Reid with CMAQ):

Reid_16<- reid_16_valid[-reid_16_del_pos,c("date", "longitude", "latitude", "PM2.5",
                     "DF_Lon", "DF_Lat", "Ens_pred", "diff_mo_ct",
                     "stateCode", "state", "GEOID", "dataset",
                     "month", "year", "season")]
names(Reid_16)<- c("date", "longitude", "latitude", "PM2.5",
                     "Lon_Reid", "Lat_Reid", "PM_Reid", "diff_mo_ct",
                     "stateCode", "state", "GEOID", "dataset",
                     "month", "year", "season")

Di_16<- di_valid[-di_del_pos,c("date", "longitude", "latitude", 
                    "PM2.5", "PM_Di")]
Di_16$Lon_Di<- di_valid$Lon[-di_del_pos]
Di_16$Lat_Di<- di_valid$Lat[-di_del_pos]
Di_16$dataset<- di_valid$group[-di_del_pos]
Di_16[,c("longitude", "latitude", "PM2.5", 
                    "Lon_Di", "Lat_Di", "PM_Di")]<- apply(Di_16[,c("longitude", 
                                                             "latitude", "PM2.5", 
                                                            "Lon_Di", "Lat_Di",
                                                            "PM_Di")],
                                                    MARGIN = 2, as.numeric)

Di_16$PM2.5<- round(Di_16$PM2.5, 3)
Reid_16$PM2.5<- round(Reid_16$PM2.5, 3)

# All_16<- inner_join(Reid_16, Di_16) # 19853 obs
# apply(All_16, MARGIN = 2, function(y) sum(is.na(y))) # missing 3 obs from Di

All_16<- full_join(Reid_16, Di_16) # 19920 obs 
apply(All_16, MARGIN = 2, function(y) sum(is.na(y))) # missing 35 obs from Reid and 35 obs from Di, but different locations and days
summary(All_16[which(is.na(All_16$PM_Reid)), "PM2.5"])
  #  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 0.000   1.312   4.292   6.383   8.042  21.250
summary(All_16[which(is.na(All_16$PM_Di)), "PM2.5"])
  # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  # 0.000   0.000   2.417  33.794  10.709 356.167

All_16$diff_mo_po<- All_16$PM2.5 - All_16$PM_Di

saveRDS(All_16, "Merged_monitor_Di_Reid_with_CMAQ.rds")


## Clean 2008-2018 data (Reid estimates without CMAQ + monitor obs):

Reid_valid<- reid_valid[-reid_del_pos,c("date", "longitude", "latitude", "PM2.5",
                     "DF_Lon", "DF_Lat", "Ens_pred", "group")]

reid_valid$state_id[-reid_del_pos]<- str_pad(reid_valid$state_id[-reid_del_pos],
                                             2, pad = "0")
reid_valid$County_FIPS[-reid_del_pos]<- str_pad(reid_valid$County_FIPS[-reid_del_pos],
                                                3, pad = "0")
reid_valid$Tract_code[-reid_del_pos]<- str_pad(reid_valid$Tract_code[-reid_del_pos],
                                6, pad = "0")
Reid_valid$GEOID<- paste0(reid_valid$state_id[-reid_del_pos], 
                          reid_valid$County_FIPS[-reid_del_pos], 
                          reid_valid$Tract_code[-reid_del_pos])

names(Reid_valid)<- c("date", "longitude", "latitude", "PM2.5",
                     "Lon_Reid", "Lat_Reid", "PM_Reid", "dataset",
                     "GEOID")
Reid_valid$diff_mo_ct<- Reid_valid$PM2.5 - Reid_valid$PM_Reid

saveRDS(Reid_valid, "Merged_monitor_Reid_without_CMAQ.rds")


## Clean EPA-monitor-based dataset (2008-2016):

epa<- readRDS("EPA_reid_n_di_08-18.rds") # actually just through 2016

EPA<- epa[c("date", "Lon", "Lat", "PM2.5", "DF_Lon", "DF_Lat", "Ens_pred",
            "Lon_Di", "Lat_Di", "PM_Di")]

epa$state_id<- str_pad(epa$state_id, 2, pad = "0")
epa$County_FIPS<- str_pad(epa$County_FIPS, 3, pad = "0")
epa$Tract_code<- str_pad(epa$Tract_code, 6, pad = "0")
EPA$GEOID<- paste0(epa$state_id, epa$County_FIPS, epa$Tract_code)

names(EPA)<- c("date", "Lon", "Lat", "PM2.5", "Lon_Reid", "Lat_Reid", "PM_Reid",
            "Lon_Di", "Lat_Di", "PM_Di", "GEOID")
apply(epa, MARGIN =2, function(y) sum(is.na(y))) # 56 missing Di estimates

saveRDS(EPA, "Merged_EPA_Di_Reid_with_CMAQ.rds")

```

